#1.16
#docker pull devopsdockeruh/heroku-example
#heroku login
#docker image push photograhb/deno-project
#docker image tag devopsdockeruh/heroku-example registry.heroku.com/dockerwithheroku/web
#docker image push registry.heroku.com/dockerwithheroku/web
#heroku container:release web
#
# https://dockerwithheroku.herokuapp.com/



