# 1.6 docker-clock
# (base) jdszsl722:1.6docker-clock jdszsl$ docker build -t docker-clock .
# (base) jdszsl722:1.6docker-clock jdszsl$ docker run docker-clock

FROM devopsdockeruh/overwrite_cmd_exercise

CMD ["-c 15"]
