version: "3.4"

services: 
  app:
    build: .
    restart: always
    volumes: 
      - ./:/app
    ports: 
      - 7777:7777
    env_file:
      - database.env

  database:
    container_name: "postgres-database"
    image: "postgres:13.1"
    restart: always
    env_file:
        - database.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  flyway:
    image: flyway/flyway:7.3.0-alpine
    env_file:
      - database.env
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate