name: Test
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        kind: ['alpine', 'centos', 'debian', 'distroless', 'ubuntu']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image
      run: |
        docker build -f ${{ matrix.kind }}.dockerfile -t ${{ matrix.kind }} .
        docker run -t ${{ matrix.kind }}
        docker run -t ${{ matrix.kind }} run https://deno.land/std/examples/welcome.ts
    - name: Test Entry Script
      if: ${{ matrix.kind != 'distroless' }}
      run: |
        docker run -t ${{ matrix.kind }} deno run https://deno.land/std/examples/welcome.ts
        docker run -t ${{ matrix.kind }} echo 'test entry script'
